### ISSUE TITLE
Build failure with trunk commit 142d3ca - Add GLU

### ISSUE THREAD

**Issue by LW-archlinux** [OoliteProject/oolite#659]
oolite trunk curreently fails to build with lots of messages like `error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode`

Bisecting showed c992c76aeaf7361348e5175941b20935e3cd22ac has no issues but the next commit 142d3caeca12192771d6cda7d67eec7312ff8a24 is the first bad commit .

for reference here's the first error that's reported 
```
src/Core/Entities/OORingEffectEntity.m: In function ‘-[OORingEffectEntity drawImmediate:translucent:]’:
src/Core/Entities/OORingEffectEntity.m:147:17: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
  147 |                 for (unsigned i = 0; i < kCircleSegments; i++)
      |                 ^~~
src/Core/Entities/OORingEffectEntity.m:147:17: note: use option ‘-std=c99’, ‘-std=gnu99’, ‘-std=c11’ or ‘-std=gnu11’ to compile your code
```

I have no idea why a change in installers/flatpak/space.oolite.Oolite.yaml would affect a sourcebuild but apparently it does.
The build commands used are 
```
  source /usr/share/GNUstep/Makefiles/GNUstep.sh
  make -f Makefile release
```

**Comment by oocube** [comment]
Interesting drill down.
So we know what kind of problems arise when. But the Github builds for the master branch never stopped working.
Is it possible the build scripts changed but you still invoke the same command? Also environment variables do play a role here.

When googling for the error I find this:
https://stackoverflow.com/questions/72497560/error-for-loop-initial-declarations-are-only-allowed-in-c99-or-c11-mode

And when searching for C99 traces in oolite I find many references. When/why did we loose them?
https://github.com/search?q=repo%3AOoliteProject%2Foolite%20c99&type=code

**Comment by mcarans** [comment]
@LW-archlinux I think this is probably a gcc specific issue. I removed some flags as I tried to clean up unneeded ones, but clearly one or more are needed for gcc. In GNUmakefile, please add the ADDITIONAL_OBJCFLAGS line below (the other lines should already exist) and let me know if that fixes it. That line used to exist with `-std=gnu99` and some other flags, but I want to clean it to just what is actually needed for the build to work to avoid confusion.

```
    ifeq ($(COMPILER_TYPE),gcc)
        ADDITIONAL_OBJCFLAGS   += -std=gnu99
        ADDITIONAL_LDFLAGS       += -fuse-ld=bfd
    else
        ADDITIONAL_LDFLAGS       += -fuse-ld=lld
    endif

```

**Comment by LW-archlinux** [comment]
Applying 
```
diff -ura oolite/GNUmakefile oolite.new/GNUmakefile
--- oolite/GNUmakefile	2026-05-28 23:42:57.290619563 +0200
+++ oolite.new/GNUmakefile	2026-05-29 00:09:23.710827927 +0200
@@ -108,6 +108,7 @@
     endif
 
     ifeq ($(COMPILER_TYPE),gcc)
+        ADDITIONAL_OBJCFLAGS     += -std=gnu99
         ADDITIONAL_LDFLAGS       += -fuse-ld=bfd
     else
         ADDITIONAL_LDFLAGS       += -fuse-ld=lld
```
to latest trunk commit 5ff4325 does fix the build problem .

That does raise the question if any of the github builds use gcc as compiler.
