### PR TITLE
SDL3 centring, fix Flatpak joystick, SquashFS appimage, gcc build

### LINKED ISSUE #555: Linux build: Default window location is suboptimal.
Testing with the appimage on 1920x1080 desktops (LinuxMint 22.3 xfce4, and AnduinOS), the splash screen manifests itself near bottom right of screen.

Also, the game window, although it remembers its size, also always appears with the bottom right corner at the bottom right of screen.

This is with the most recent appimage in a fresh folder.  Same happens when testing with my usual OXP heap.

### LINKED ISSUE #654: Fix joystick not detected with Flatpak (affects SDL1.2 and 3)
Joysticks are not detected with Flatpak on SDL1.2 and SDL3: https://bb.oolite.space/viewtopic.php?t=22104

It is a permissions issue: `flatpak override --system --device=all space.oolite.Oolite` is a workaround.

### LINKED ISSUE #656: Oolite game window icon missing
Before modern builds the Oolite main window used to have the Oolite icon in Gnome Dash. Now there is the generic cog:

Image

It means the StartupWMClass or Icon settings are no longer suitable and should be checked:
https://github.com/OoliteProject/oolite/blob/master/installers/FreeDesktop/space.oolite.Oolite.desktop

I spotted this when running oolite_dev-1.93.1-70-x86_64.AppImage.

### LINKED ISSUE #659: Build failure with trunk commit 142d3ca - Add GLU
oolite trunk curreently fails to build with lots of messages like `error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode`

Bisecting showed c992c76aeaf7361348e5175941b20935e3cd22ac has no issues but the next commit 142d3caeca12192771d6cda7d67eec7312ff8a24 is the first bad commit .

for reference here's the first error that's reported 
```
src/Core/Entities/OORingEffectEntity.m: In function ‘-[OORingEffectEntity drawImmediate:translucent:]’:
src/Core/Entities/OORingEffectEntity.m:147:17: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
  147 |                 for (unsigned i = 0; i < kCircleSegments; i++)
      |                 ^~~
src/Core/Entities/OORingEffectEntity.m:147:17: note: use option ‘-std=c99’, ‘-std=gnu99’, ‘-std=c11’ or ‘-std=gnu11’ to compile your code
```

I have no idea why a change in installers/flatpak/space.oolite.Oolite.yaml would affect a sourcebuild but apparently it does.
The build commands used are 
```
  source /usr/share/GNUstep/Makefiles/GNUstep.sh
  make -f Makefile release
```

### PR DESCRIPTION
**Pull request by mcarans**
Fixes https://github.com/OoliteProject/oolite/issues/656
Fixes https://github.com/OoliteProject/oolite/issues/654
Fixes https://github.com/OoliteProject/oolite/issues/555
Fixes https://github.com/OoliteProject/oolite/issues/659

### CODE REVIEW

**Review by oocube — DISMISSED** [review]

**Comment by HiranChaudhuri** [comment]
#656  is not fixed. Hopefully the issue does not get closed when this PR gets merged for the other two issues.

**Review by oocube — DISMISSED** [review]

**Comment by mcarans** [comment]
@oocube is the splash and game window centred for you? This PR doesn't use the separate splash launcher binary and tries to do centring with the game's built in splash.

**Comment by mcarans** [comment]
Tested on Windows and Kubuntu 26.04 - works fine.

**Comment by oocube** [comment]
> @oocube is the splash and game window centred for you? This PR doesn't use the separate splash launcher binary and tries to do centring with the game's built in splash.

I tested oolite_dev-1.93.1-PullRequest658.181-x86_64.AppImage on my multi-monitor setup.
The splash screen is perfectly centered on the right (=main) screen. The main window does not come up centered.

Usually I play by moving the main screen to the center monitor and maximize it. When I stop the game and run again, the splash screen is perfectly centered on the right (=main) screen. The game window also comes up maximized but on the right (main) screen. I would have expected it to remember size and position, but my expectation may be wrong here.

**Comment by mcarans** [comment]
@oocube Thanks for testing. Where does the main window appear if it is not maximised on first launch of the game? How does that compare with behaviour on master? Did previous versions of Oolite remember position?

What is the desired behaviour here? I think it's now possible to get the particular display a window is on in a multi monitor setup so it may be possible to store it, but I'd prefer to look at that in a future PR.

For this PR if I can make things at least the similar to what 1.92.1 did regarding centring but without the separate splash launcher, then that is a start and we can look at proper multi monitor support in another PR. Is what happens in this PR and/or master worse than 1.92.1?

Here is what I found:
I tried making a dual monitor setup with my laptop and monitor using monitor as primary.

1.92.1 and current master behave largely the same with the splash and game launching centred on primary.

PullRequest658.181 launches splash and game centred on primary if I launch from a file explorer on primary or on secondary if I launch from a file explorer on secondary.

Position is not remembered on any of them, but size is.

**Comment by oocube** [comment]
> @oocube Thanks for testing. Where does the main window appear if it is not maximised on first launch of the game? How does that compare with behaviour on master? Did previous versions of Oolite remember position?

Actually it is not important that they remember position or come up as maximized or centered. It takes me one drag operation to move the window to the top of the preferred screen.
 
> What is the desired behaviour here? I think it's now possible to get the particular display a window is on in a multi monitor setup so it may be possible to store it, but I'd prefer to look at that in a future PR.

Am not sure myself. If at all, I'd put my money on remembering the screen position and size. Which again is annoying in case you have less screens than you used to have. OoliteStarter will come with a minimum meaningful size, centered where the splash screen is. The splash screen comes up centered on the main screen - but even while it is there and the application is loading you can already drag it elsewhere, and that's where the main screen will then pop up. For Oolite - since I never play in a window having it maximized is the normal condition but it does not hurt.

There is something that hurts much more is the window resize, which I already documented in
https://bb.oolite.space/viewtopic.php?p=305317
I just tested oolite_dev-1.93.1-PullRequest658.181-x86_64.AppImage and it is even worse - I can not shrink the window at all.
 
> For this PR if I can make things at least the similar to what 1.92.1 did regarding centring but without the separate splash launcher, then that is a start and we can look at proper multi monitor support in another PR. Is what happens in this PR and/or master worse than 1.92.1?

Fair enough. I also get the feeling this PR has become too complex already. Let's target less issues per PR in future so they can be tested and merged without blocking each other.
 
> Here is what I found: I tried making a dual monitor setup with my laptop and monitor using monitor as primary.
> 
> 1.92.1 and current master behave largely the same with the splash and game launching centred on primary.

Here are two screenshots of oolite_dev-1.93.1-PullRequest658.181-x86_64.AppImage launching after it has no longer been maximized in the previous run:

Screenshot from 2026-05-30 08-20-45


Screenshot from 2026-05-30 08-20-50

> PullRequest658.181 launches splash and game centred on primary if I launch from a file explorer on primary or on secondary if I launch from a file explorer on secondary.
> 
> Position is not remembered on any of them, but size is.

That would explain why centering matters. But: My main screen has less resolution than the screen I play on. So Oolite should have problems restoring the size while at the same time centering on the main screen. As mentioned before, it is not too bad. Let's move on.

**Comment by mcarans** [comment]
@oocube Below video shows resizing on my system. It is smooth, so not sure how to replicate the issue you're having with resizing especially not the problem with shrinking the window:
https://github.com/user-attachments/assets/e175da36-0d92-419e-98d8-2209466d84f5

What desktop environment are your running?

**Comment by oocube** [comment]
> @oocube Below video shows resizing on my system. It is smooth, so not sure how to replicate the issue you're having with resizing especially not the problem with shrinking the window: https://github.com/user-attachments/assets/e175da36-0d92-419e-98d8-2209466d84f5

Ok, then we have one "works for me" vs one "does not work for me". Let's follow up the resize in a separate issue.
From my screenshots you can see the window is not centered. That's what you were aiming for, right?

**Comment by mcarans** [comment]
> > @oocube Below video shows resizing on my system. It is smooth, so not sure how to replicate the issue you're having with resizing especially not the problem with shrinking the window: https://github.com/user-attachments/assets/e175da36-0d92-419e-98d8-2209466d84f5
> 
> Ok, then we have one "works for me" vs one "does not work for me". Let's follow up the resize in a separate issue. From my screenshots you can see the window is not centered. That's what you were aiming for, right?

I also tested resizing when dual screen and it is smooth for me, so yes please make a separate issue for the problem you are having to see if anyone else also has the problem. What distro and desktop environment do you have?

I expected both splash and game window to be centred. If this SDL 3 code doesn't work for centring windows, then I expect that window positioning is unlikely to work because it would suggest that the window manager ignores positioning requests on some systems (that's not what happens on my system). It could be a Wayland bug.

What happens if you make the game window much smaller (assuming that's possible given the sizing bug you found)? I can't tell very well from the screenshot but it looks like the game window although windowed and not fullscreen might be larger than the screen resolution?

**Comment by oocube** [comment]
I just noticed something interesting on oolite_dev-1.93.1-70-x86_64.AppImage:
It remembers the window position and size perfectly. So when I start the game it has a centered splash screen, then just goes back to my middle screen in maximized mode.


Screenshot from 2026-05-30 22-24-46


Screenshot from 2026-05-30 22-25-17


Screenshot from 2026-05-30 22-25-27

**Comment by mcarans** [comment]
@oocube it doesn't do that for me. Maybe your window manager stores the position? To my knowledge, there is nothing in the code for that.

**Comment by mcarans** [comment]
@oocube I have made a new version: https://github.com/OoliteProject/oolite/actions/runs/26704575278. Please let me know if that fixes centring for the game window. 

I added an explicit call to centre rather than just relying on the earlier request:

```
	SDL_HideWindow(window);
	SDL_SetWindowSize(window, firstScreen.width, firstScreen.height);
	SDL_SetWindowPosition(window, SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED);
	SDL_SetWindowFullscreen(window, fullScreen);
	SDL_ShowWindow(window);

```

**Comment by oocube** [comment]
I tested oolite_dev-1.93.1-PullRequest658.183-x86_64.AppImage and here is what it looks like:


Screenshot from 2026-05-31 08-47-27


Screenshot from 2026-05-31 08-47-37


Screenshot from 2026-05-31 08-47-44

**Review by oocube — APPROVED** [review]

**Comment by mcarans** [comment]
Lonewolf reports centred now. Looks centred from images above. Merging.
