### ISSUE TITLE
Oolite 1.93.1-kja-sdl3.2 build fails on Debian 13

### ISSUE THREAD

**Issue by jwiz456** [OoliteProject/oolite#660]
src/SDL/MyOpenGLView.m:1717:6: error: call to undeclared function 'SDL_SavePNG'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1717 |         if(!SDL_SavePNG(tmpSurface, [pathToPic UTF8String]))
      |             ^
et al ...

Why is this even here?
SDL_SavePNG is a feature available only with SDL 3.4.0 and later.

**Comment by mcarans** [comment]
The SDL version in Oolite has been upgraded from 1.2 to 3.4 (not 3.2). I had the same issue while testing the SDL 3 PR. I found it is possible to make it work with SDL 3.2 by including the SDL 3 image library and adding include and lib. However, since I anyway planned to upgrade from Kubuntu 25.10 to 26.04 (which has SDL3.4), I just did that. AI claims the easiest option to obtain 3.4 is to build SDL from source:

```
# Install the standard development headers needed for SDL3 backends
sudo apt install build-essential cmake ninja-build libwayland-dev libx11-dev libegl-dev libxkbcommon-dev libpipewire-0.3-dev libpulse-dev

# Clone and build the specific release branch
git clone https://github.com/libsdl-org/SDL.git -b SDL3
cd SDL
mkdir build && cd build
cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local ..
ninja
sudo ninja install
```

**Comment by LW-archlinux** [comment]
```
$ git clone https://github.com/libsdl-org/SDL.git -b SDL3
Cloning into 'SDL'...
fatal: Remote branch SDL3 not found in upstream origin
$ 
```

`git clone https://github.com/libsdl-org/SDL.git -b release-3.4.x` does work .

**Comment by mcarans** [comment]
Or to get a specific released version you can use the tag eg. https://github.com/libsdl-org/SDL/tree/release-3.4.8 eg.
`git clone https://github.com/libsdl-org/SDL.git --depth 1 -b release-3.4.8`

**Comment by mcarans** [comment]
Closing info provided
